version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      -  DEV_DB_USERNAME=${DEV_DB_USERNAME}
      -  DEV_DB_PASSWORD=${DEV_DB_PASSWORD}
      -  DEV_DB_NAME=${DEV_DB_NAME}
      -  DEV_DB_HOSTNAME=${DEV_DB_HOSTNAME}
      -  DEV_DB_DIALECT=${DEV_DB_DIALECT}
      -  DEV_DB_LOGGGIN=${DEV_DB_LOGGGIN} 

    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3001:30001"
    environment:
      - NODE_ENV=production
      - API_URL=http://3.68.84.203:3000

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      -  MYSQL_ROOT_PASSWORD=root
      -  MYSQL_DATABASE=test
      -  DEV_DB_USERNAME=${DEV_DB_USERNAME}
      -  DEV_DB_PASSWORD=${DEV_DB_PASSWORD}
      -  DEV_DB_NAME=${DEV_DB_NAME}
      -  DEV_DB_HOSTNAME=${DEV_DB_HOSTNAME}
      -  DEV_DB_DIALECT=${DEV_DB_DIALECT}
      -  DEV_DB_LOGGGIN=${DEV_DB_LOGGGIN}
      
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
